### ISSUE TITLE
Add associate-eip to the documentation

### ISSUE THREAD

**Issue by fletchowns** [chef/knife-ec2#244]
There is currently no mention of this option in the README, I only found out about it from a StackOverflow post that mentioned it.

**Comment by jamescott** [comment]
I would like to know more about the possible values for the --server-connect-attribute option as well. Ideally, we could add a "for example: ``foo`` to that description that shows the most common usage.

The option itself is on the page: http://docs.chef.io/plugin_knife_ec2.html#id2

It's at the very top of that list because the options are grouped by short name, which in this case is ``-a``.

**Comment by kaustubh-d** [comment]
Possible values for `--server-connect-attribute` are 'dns_name', 'public_ip_address' and 'private_ip_address'

**Comment by tiago-cruz-movile** [comment]
May I suggest to put these values in '--help'?

```
$ knife ec2 server create --help | grep server-connect-attribute -C 2
    -G, --groups X,Y,Z               The security groups for this server; not allowed when using VPC
    -a ATTRIBUTE,                    The EC2 server attribute to use for SSH connection. Use this attr for creating VPC instances along with --associate-eip
        --server-connect-attribute
        --spot-price PRICE           The maximum hourly USD price for the instance
        --spot-request-type TYPE     The Spot Instance request type. Possible values are 'one-time' and 'persistent', default value is 'one-time'
```

Using '--server-connect-attribute private_ip_address' worked for me to access one VPC instance where the DNS does not works.

**Comment by siddheshwar-more** [comment]
@tiago-cruz-movile 

Please check your VPC DNS settings, i.e `DNS resolution: ` and `DNS hostnames: ` should be set to ***yes***

Please share your `ec2 server create ...` command. details with stdout logs

Thanks!
