### ISSUE TITLE
Secret file not created for Windows instances

### ISSUE THREAD

**Issue by odlevakp** [chef/knife-ec2#248]
Using the option `--secret-file` does work for Linux instances, but when launching a Windows server it is not created. Tried different paths (containing ~, absolute ones), specifying `--secret` or putting `knife[:secret_file]` to knife.rb. Nothing works:
```
FATAL: ArgumentError: No secret specified to load_secret and no secret found at C:\chef\encrypted_data_bag_secret
```

Currently I need to log in to the instance using RDP and create `C:\chef\encrypted_data_bag_secret` manually, then re-run chef client which is really annoying.

**Comment by Scythril** [comment]
I'm having this problem as well. What's even stranger is, if I turn around and call `knife bootstrap windows winrm` with the `--secret-file` option, it DOES upload the file. I'd rather not have to call 2 different commands with the same options to get a server up and running.

**Comment by Scythril** [comment]
When looking at the code, the `--secret-file` option in knife-ec2 maps to the chef config `secret_file`, while in knife-windows the `--secret-file` option maps to the chef config `encrypted_data_bag_secret_file`. I'm not sure what the difference is. Could someone with more knowledge of these options tell me if I'm doing something wrong?

**Comment by NimishaS** [comment]
@odlevakp , @Scythril  we are looking at this issue

**Comment by prabhu-das** [comment]
You can try server create with- 

1. Add below line to your knife.rb file instead of using `--secret-file` option from CLI
` knife[:encrypted_data_bag_secret_file] = "secret-file" ` 

OR

2 . You can use  `--secret-file` option with this change- https://github.com/chef/knife-ec2/pull/279 .

Actually we should update `knife-windows` https://github.com/chef/knife-windows/blob/master/lib/chef/knife/bootstrap_windows_base.rb#L94-L96    to 
```        
 option :secret_file,
        :long => "--secret-file SECRET_FILE",
        :description => "A file containing the secret key to use to encrypt data bag item values. 
         Will be rendered on the node at c:/chef/encrypted_data_bag_secret and set
         in the rendered client config."
```
And update windows bootstrap template accordingly.

Ideally, knife-windows option should be consistent with chef's **--secret-file** option -
https://github.com/chef/chef/blob/master/lib/chef/knife/data_bag_secret_options.rb#L45-L48 

Thank you !

**Comment by Scythril** [comment]
Does this mean removing the `encrypted_data_bag_secret_file` option entirely from the command-line? That's not where I was trying to go at all!

It would be helpful to standardize on these options, though.
