### ISSUE TITLE
Support for EBS volume encryption in knife-ec2 server create options?

### ISSUE THREAD

**Issue by rfackett** [chef/knife-ec2#277]
I see that support for GP2 EBS volumes was added (the wiki needs to be updated), but I was wondering if there was support, or a workaround, to take advantage of AWS EBS Volume Encryption in the knife ec2 server create?

**Comment by siddheshwar-more** [comment]
@rfackett -
Hey, we are looking into this...

**Comment by rfackett** [comment]
@siddheshwar-more thank you, any potential work-around in the mean time?

**Comment by siddheshwar-more** [comment]
@rfackett 
FYI -
Actually **knife-ec2** uses [fog](https://github.com/fog/fog) lib to deal with **AWS**. And we found **fog**  has support for encrypted ebs volume. So, currently we are working on this feature.

**Comment by rfackett** [comment]
@siddheshwar-more thanks for following up.  Do you have an ETA on when this will be supported?

**Comment by kaustubh-d** [comment]
@rfackett  We have included option for EBS volume encryption please refer this patch https://github.com/chef/knife-ec2/pull/280. Could you please try and let us know the results ?

**Comment by pjungwir** [comment]
@kaustubh-d Thanks for your commit! I'm not the OP, but I'm trying it out. I'm finding that when I say `knife ec2 server create --ebs-encrypted ...` I get timeout errors from fog, but the instances come up quickly if I leave off the new option. Did you encounter that? It doesn't seem too surprising. How did you work around it?

**Comment by Vasu1105** [comment]
@pjungwir Could you please let us know the command that you are trying ?

**Comment by pjungwir** [comment]
It was something like this:

`knife ec2 server create -I ami-xxxx -f m3.medium -Z us-east-1b -E staging -r 'role[web]' --server-connect-attribute private_ip_address --ssh-user ubuntu --ssh-gateway ec2-user@bastion.example.com --identity-file ~/src/example/doc/it/aws/pjungwir.pem -S pjungwir --subnet subnet-xxxx -g sg-xxxx -N staging-web-1 --iam-profile staging-web --region us-east-1 --ebs-encrypted`

I think the extra time to provision an encrypted volume might be unavoidable. My current workaround is to use the `aws_ebs_volume` resource in a recipe (from the `aws` cookbook), and I have to pass that a `timeout` attribute there because with its default it often times out too. So adding an option to `ec2 server create` to extend the timeout waiting for an instance might be nice.

**Comment by siddheshwar-more** [comment]
@pjungwir -

In your case, the Fog Timeout error is because of missing --ebs-size option 

So, In #299 I've added validation for --ebs-size and --ebs-encrypted combo. And also added new option called `--aws-connection-timeout MINUTES` for aws API connection timeout.

Normally default  --aws-connection-timeout i.e 10 min is enough for knife ec2 server create . This option is only helpful when AWS is slow and taking more than 10 min time to create server.

**Comment by siddheshwar-more** [comment]
@pjungwir have you tried it with `--ebs-size` option

**Comment by gbish** [comment]
Hello,

I think I've found the solution to your problem at last, read it here please <http://jefrinkishe.jobrackassociates.com/oihdmp>

Bests, hebgb@blueyonder.co.uk
