### ISSUE TITLE
~/.aws/config file is not used

### ISSUE THREAD

**Issue by fletchowns** [chef/knife-ec2#398]
The `~/.aws/credentials` file is used which is great, but the `~/.aws/config` file doesn't seem to get used by `knife ec2`.

For example, I've got the following `~/.aws/config`:
```
[default]
region=us-west-1
```

But when I do `knife ec2 server list` it defaults to us-east-1:
```
$ knife ec2 server list
WARNING: No region was specified in knife.rb or as an argument. The default region, us-east-1, will be used:
Instance ID  Name  Public IP  Private IP  Flavor  Image  SSH Key  Security Groups  IAM Profile  State
```

I know you can specify the region in knife.rb but it would be cool if it also looked at `~/.aws/config`.

Link to aws cli docs for reference: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files

**Comment by NimishaS** [comment]
@fletchowns , we have added support for this https://github.com/chef/knife-ec2/pull/399

Please use the master branch.

**Comment by fletchowns** [comment]
@NimishaS works great with master branch. Thank you for this feature!

**Comment by vinyar** [comment]
Ahoy. I just tried and I'm hitting the same error with config file not being read using

**Comment by Vasu1105** [comment]
@vinyar 
1) 0.12.0 don't have support for :aws_config_file option.
2) We checked with "master" and everything works fine. What we tired is as you mentioned we added the values in knife.rb i.e. 
knife[:aws_access_key_id] = env['AWS_ACCESS_KEY']
knife[:aws_secret_access_key] = env['AWS_SECRET_KEY']
knife[:aws_config_file] = '/Users/alexvinyar/.aws/config'

If we specify the region in aws config file it picks it up from config file otherwise it sets the default region and we not received any error which complains about region not specified. We tried both server create and server list commands and everything is working fine. 

Could you please give us more details what command you are trying and your configuration settings ?

**Comment by NimishaS** [comment]
@vinyar , verified once again with the master branch. If the following is passed in `knife.rb` file:

**Comment by NimishaS** [comment]
@vinyar , we verified once again with the master branch. The following is passed in `knife.rb` file:
```
knife[:aws_access_key_id] = env['AWS_ACCESS_KEY']
knife[:aws_secret_access_key] = env['AWS_SECRET_KEY']
knife[:aws_config_file] = '/Users/alexvinyar/.aws/config'
```
If no region is specified in the `/Users/alexvinyar/.aws/config` file, then the default `us-east-1` region is picked up.

Closing this issue. Please re-open if you still face the issue.

**Comment by NimishaS** [comment]
Note: These changes are not released yet.

**Comment by fletchowns** [comment]
Thanks for the enhancement. Although, one question. It seems that `~/.aws/credentials` and `~.aws/config` are fairly standard locations for these files. How come we have to specify this in knife.rb?
```
knife[:aws_credential_file] = File.join(ENV['HOME'], ".aws", "credentials")
knife[:aws_config_file] = File.join(ENV['HOME'], ".aws", "config")
```

It seems like it should automatically check those locations by default, even if they aren't specified as such in knife.rb
