### ISSUE TITLE
knife ec2 Cannot find SSH Identity file, required to fetch dynamically generated password

### ISSUE THREAD

**Issue by ditjhaba** [chef/knife-ec2#411]
Good day,

I am struggling to bootstrap an ec2 instance. The `knife ec2 server create` is able to create an instance but takes a long time to bootstrap. And when it eventually did, it gave me this error:

`ERROR: Cannot find SSH Identity file, required to fetch dynamically generated password` 

I have a knife.rb file and it's contents are as below:

**_knife[:aws_access_key_id] = "access-key"
knife[:aws_secret_access_key] = "secret-key"
knife[:ssh_key_name] = 'key-name'
knife[:region] = "us-west-2"
knife[:winrm_port] = 5985_**

This content has all the necessary keys for the server and the pem file resides in the .ssh/ directory.

My questions are as follows:
1. Why does it takes so long (I am talking hours) to bootstrap the instance?
2. Why am I failing to RDP into the instance?
3. Where should the pem file be so that it can picked up by the `knife ec2 server create`?

Thank you

**Comment by Vasu1105** [comment]
@ditjhaba could you please provide the command that you are using for server create.

**Comment by ditjhaba** [comment]
Hi @Vasu1105 

Here is the command:

`knife ec2 server create --node-name kmc-server -I ami-df8767bf -f t2.micro'

**Comment by Vasu1105** [comment]
@ditjhaba  use --ssh-key (ssh key is nothing but the key pair name that you generate using ec2 portal) and --identity-file (path to your pem file) options in you ec2 command 
Ref: http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-key-pairs.html

**Comment by ditjhaba** [comment]
@Vasu1105
 
ERROR: Fog::Compute::AWS::NotFound: The key pair '~/.ssh/ditjhaba.pem' does not exist.

This is an error that I am getting.

**Comment by rizvanjavid** [comment]
@ditjhaba 
The above error is because you have mentioned full path against knife[:ssh_key_name] inside your knife.rb
Solution:
1. Make sure that ditjhaba.pem  resides in ~/.ssh directory with read write permission.
2. Instead of mentioning the full path just mention the name of your  ditjhaba.pem without .pem
    extension.
3. Inside your knife.rb replace 
    knife[:ssh_key_name] =  '~/.ssh/ditjhaba.pem    by 
    knife[:ssh_key_name] = "ditjhaba"
 .......

From your question it is not clear that, how you are  bootstrapping you instance, is it by passing the username & password or by passing identity file??
Bootstrap  is taking more time in the scenarios where it is unable to communicate with the spawned VM, it can be because of firewall issues (Security Group).

**Comment by dheerajd-msys** [comment]
@ditjhaba From your question 2, it seems you are trying to provision windows vm . So in case of windows vm provisioning you need to use three more parameter `--winrm-transport ssl --winrm-ssl-verify-mode verify_none --security-group-ids <security-group-id>` . Also make sure you provide name instead of path for  `knife[:ssh_key_name]` .
Command should look like : 
`knife ec2 server create --node-name kmc-server -I ami-df8767bf -f t2.micro -x  .\<username> -P "<password>" --winrm-transport ssl --winrm-ssl-verify-mode verify_none  --security-group-ids <security-groupId>`
`--security-group-ids` should have ports `5985, 5986, 3389` added.

**Comment by dheerajd-msys** [comment]
Hope comments added above will help you to resolve your issue.
Closing now. Thanks.
