### ISSUE TITLE
Data bags decryption is not working ?

### ISSUE THREAD

**Issue by valterhenrique** [chef/knife-ec2#491]
Hi,
I'm trying to create/bootstrap an ec2 instance. My recipe use the cookbook `users` from chef. These users have their own SSH keys defined. I've encrypted them and upload to my chef-server, which I can verify using Chef Manage web interface.

My current command is:

`
knife ec2 server create -r 'recipe[company_base]' -I ami-315a975e --groups default,chef-test --ssh-key devops -f t2.medium --ssh-user ubuntu --identity-file ~/.ssh/devops.pem --secret-file .chef/encrypted_data_bag_secret
`

And when I ran the command above my recipe is able to provision until the end, however it doesn't show the desired output which should create my users based on what was defined on my data bags.

> current_dir = File.dirname(__FILE__)
> log_level                :info
> log_location             STDOUT
> node_name                "vasi"
> client_key               "#{current_dir}/vasi.pem"
> validation_client_name   "company-validator"
> validation_key           "#{current_dir}/company-validator.pem"
> chef_server_url          "https://chef.company.com/organizations/company"
> cookbook_path            ["#{current_dir}/../cookbooks"]
> knife[:aws_credential_file] = "/home/vasi/.aws/credentials"
> knife[:aws_config_file] = "/home/vasi/.aws/config"
> knife[:region] = "eu-central-1"
> knife[:ssh_key_name] = "devops"

This is my current `knife.rb` file. What I'm missing here ? Is there any way to provide my `data bag secret` to `knife-ec2` ? Any suggestion would be very appreciated!

PS: Why the argument `--secret-file` is not documented on the README ? I just found out about it [here](https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_server_create.rb#L223).

Best regards,
Valter.

**Comment by dheerajd-msys** [comment]
@valterhenrique, I tried using the `encrypted_data_bags` with `knife ec2 server create` command and it worked successfully for me. Here is the command that I tried:
```
knife ec2 server create -N ubuntu1 -r "recipe[databag_cookbook]" -I ami-5ac2cd4d -f t2.micro -S Ash1 -i <identity_file> --ssh-user ubuntu --region us-east-1 -Z us-east-1a --secret-file D:\chef-repo\encrypted_data_bag_secret
```

Few points to be noted:
1. While creation of the `secret_file`, I had to save it in UTF-8 encoded format.
2. Here are my recipe contents:
```
passwords = Chef::EncryptedDataBagItem.load('databag_1', 'mysql')
pass = passwords['pass']
user = passwords['user']
Chef::Log.info("The pass is: '#{pass}' & user : #{user}")
```
3. I observed something strange. When I was using double quotations like: `Chef::EncryptedDataBagItem.load("databag_1", "mysql")`, the decryption failed. However it worked successfully with single quotes.

Please let us know if this helps in resolving your issue. In case your issue is not resolved, please share all the steps that you followed including the recipe that you are running.

**Comment by valterhenrique** [comment]
Hi @dheerajd-msys, thank you for you reply, now it worked!
