### ISSUE TITLE
node-ssl-verify-mode none flag is ignored

### ISSUE THREAD

**Issue by rudymccomb** [chef/knife-ec2#497]
I'm trying to create an ec2 server with the SSL disabled 

`knife ec2 server create \
--node-ssl-verify-mode none`

The flag is getting ignored, this does not seem to be the issue on older versions of ChefDK.

`chef --version`

`Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0 
knife-ec2-0.15.0`

`ERROR: SSL Validation failure connecting to host: chef-server.node.com - SSL_connect returned=1 errno=0 state=error: certificate verify failed`

`Unexpected Error:
OpenSSL::SSL::SSLError: SSL Error connecting to https://chef-server.node.com/organizations/node.com - SSL_connect returned=1 errno=0 state=error: certificate verify failed`

**Comment by rudymccomb** [comment]
turns out this is an issue when using a wildcard cert as described https://github.com/chef/chef-server/issues/927

**Comment by NAshwini** [comment]
Hi @Rudy McComb
I am able to run successfully with 
`knife ec2 server create --node-name AshWin4 -I ami-11e84107 -f t2.micro -x '.\Ashwini' -P "ec2user@123" --winrm-transport ssl --winrm-ssl-verify-mode verify_none --node-ssl-verify-mode none -VV `  command.
The error you are facing is due to `unverified certificate`. 
you can refer the link "https://docs.chef.io/server_security.html#knife-chef-client"

we need to make some setting in `/etc/opscode/chef-server.rb` for successfull run
reference link :
https://docs.chef.io/config_rb_server.html#ssl-protocols
https://docs.chef.io/config_rb_server_optional_settings.html#nginx

**Comment by NAshwini** [comment]
@rudymccomb , any updates on this?

**Comment by NimishaS** [comment]
@rudymccomb , closing this issue since @NAshwini was able to get the command running successfully.

Please feel free to reopen if you still have any difficulty.
