### ISSUE TITLE
Possible to create additional network interface during bootstrap?

### ISSUE THREAD

**Issue by breisig** [chef/knife-ec2#564]
I am running the latest knife-ec2 (0.19.16) and wondering if their is a way to create an additional network card (eth1) and assign it an IP (Using a specific subnet id for that secondary network card) during initial server creation? (knife ec2 server create)

It's frustrating having only the option to create the EC2 instance with the web interface and creating + assigning during VM creation.

**Comment by tas50** [comment]
The goal of knife-ec2 is to support *most* use cases for a basic system bootstrap in EC2 with Chef installed. After a certain point it's really better to use a tool like Terraform to build out complex environments and bootstrap Chef Infra onto those nodes. I'm going to close this since it feels like it's outside the scope of basic system setup.
