### ISSUE TITLE
ERROR: undefined method `[]' for nil:NilClass when using --ebs-encrypted

### ISSUE THREAD

**Issue by breisig** [chef/knife-ec2#565]
It seems when I try to launch/bootstrap a new instance (knife ec2 server create) and add the "--ebs-encrypted" option to the command (to make it encrypted), it always get an error.

ERROR: undefined method `[]' for nil:NilClass

I am the latest knife-ec2 (0.19.16) and the AMI image used is originally *not* encrypted.

knife ec2 server create test.my-server.com -N test.my-server.com  --image ami-0a434d5g236d24153 -f m4.large --ssh-key ssh-aws --ssh-user root --identity-file ~/ssh-aws.pem --subnet subnet-5074a552 -g sg-184fe554 --environment production --run-list 'role[base-minimal]' --ebs-optimized --ebs-size 80 -A --server-connect-attribute public_ip_address --private-ip-address 10.0.0.4 --associate-eip 3.3.3.3 --no-host-key-verify --ebs-encrypted
ERROR: undefined method `[]' for nil:NilClass

**Comment by dheerajd-msys** [comment]
Hi @breisig, 

Could you please try with latest release of `knife-ec2`. This issue has been fixed in `knife-ec2 v1.0.7`. There are some parameter updates  like `--[no-]host-key-verify`  to `--ssh-verify-host-key VALUE`. 

FYI, https://github.com/chef/chef/blob/master/RELEASE_NOTES.md

Please revert in case you have any issues.

**Comment by dheerajd-msys** [comment]
@breisig Closing this issue for now. 
Please feel free to re-open if you face issues with latest version.
